import java.util.HashMap;

//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : AttendanceManager.java
//  @ Date : 1/8/2014
//  @ Authors : Meher, Nikhila, Omair, Harika 
//
//




public class AttendanceManager {
	public HashMap<Course,Integer> getAttendanceByStudent(Student student) {
		return null;
	
	}
	
	public HashMap<Student,Integer> getAttendanceByCourse(Course course) {
		return null;
	}
	
	public HashMap<Course,HashMap<Student,Integer>> getAttendanceReport() {
		return null;
	}
	
	public void addAttendance(Student student, Course course) {
		return;
	}
}
