//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : Course.java
//  @ Date : 1/8/2014
//  @ Author : Meher, Harika, Omair, Nikhila
//
//

//What will happen now?


public class Course {
	public String courseName;
	public String courseID;
	public String syllabus;
	public int duration;
	public int numOfClassesPerWeek;
	public int numOfCredits;
	public String questionPaper;
}
