import java.util.List;

//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : DataHelper.java
//  @ Date : 1/8/2014
//  @ Author : Meher, Harika, Omair, Nikhila
//
//

//when I push i should push only files and not properties or .project files. (Meher)



public class DataHelper {
	int a = 123;
	public List<Course> viewAllCourse() {
		return null;
	}
	
	public List<Student> viewAllStudentsByCourse(Course course) {
		return null;
	}
	
	public String getQuestionPaper(Course course) {
		return null;
	}
}
