import java.util.Date;
import java.text.SimpleDateFormat;
import java.util.HashMap;
import java.util.List;
import java.util.Scanner;

//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : ExamBranch.java
//  @ Date : 1/8/2014
//  @ Author : Meher, Harika, Omair, Nikhila
//
//




public class ExamBranch {
	public String examBranchID;
	String password;
	HashMap<Course, Date> exams = new HashMap<>();
	DataHelper dH = new DataHelper();
	
	
	/**
	 * Method to Schedule Exam
	 * based on course
	 * 
	 */
	@SuppressWarnings("resource")
	public void scheduleExams() {
	
		try {
			
			System.out.println("\n--Schedule Exams--\n");
			System.out.println("Courses available are:\n");
			for(int i = 0; i<dH.list_Course.size(); i++)
			{
				System.out.print(dH.list_Course.get(i));	//prints the courses
				System.out.println("\t----"+i);
			}
			System.out.println("Select the course that you want to schedule an exam for: ");
			Scanner scan = new Scanner(System.in);
			Integer selection = scan.nextInt();				//get the course selected
			Course selectedCourse = dH.list_Course.get(selection);
			
			System.out.println("The selected course is: "+selectedCourse);
			System.out.println("Enter the Date of the exam: (yyyy-MM-dd)");
			String d = scan.next();
			SimpleDateFormat ft = new SimpleDateFormat("yyyy-MM-dd");	//get the date
			Date examDate = ft.parse(d);
			
			exams.put(selectedCourse, examDate);				//put the date in hashmap
			
			System.out.println("Exam Scheduled!");
			System.out.println(exams);
			
		} catch (Exception e) {
			System.err.println("Unexpected Error Occurred!");
		}
		
	}
	
	/**
	 * Method to update the attendance of students attending exam of 
	 * particular course
	 * 
	 */
	@SuppressWarnings("resource")
	public void updateAttendanceByExam() {
		try {
			System.out.println("Update the Attendance of students by Exam");
			System.out.println("Courses are:\n");
			for(int i = 0; i<dH.list_Course.size(); i++)
			{
				System.out.print(dH.list_Course.get(i));	//show all courses
				System.out.println("\t----"+i);
			}
			System.out.println("Select the course exam that you want to give attendance for: ");
			Scanner scan = new Scanner(System.in);
			Integer selection = scan.nextInt();				//get selected course
			Course selectedCourse = dH.list_Course.get(selection);
			
			AttendanceManager attendance = new AttendanceManager();
			List<Student> students = dH.viewAllStudentsByCourse(selectedCourse);	//get all students attending that course
			for(int i = 0; i<students.size(); i++)
				attendance.addAttendance(students.get(i), selectedCourse);		//add attendance of the students
			
			System.out.println("Updated Attendance of students!");
		} catch (Exception e) {
			System.err.println("Unexpected Error Occurred!");
		}
	}
	
}
