//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : ExamBranch.java
//  @ Date : 1/8/2014
//  @ Author : Meher, Harika, Omair, Nikhila
//
//




public class ExamBranch {
	public String examBranchID;
	String password;
	public void scheduleExams() {
	
	}
	
	public void updateAttendanceByExam() {
	
	}
}
