import java.util.HashMap;

//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : MarksManager.java
//  @ Date : 1/8/2014
//  @ Author : Meher, Harika, Omair, Nikhila
//
//




public class MarksManager {
	public HashMap<Course,Integer> getMarksByStudent(Student student) {
		return null;
	}
	
	public HashMap<Student,Integer> getMarksByCourse(Course course) {
		return null;
	}
	
	public HashMap<Course,HashMap<Student,Integer>> getMarksReport() {
		return null;
	}
	
	public void addMarks(Student student, Course course, int marks) {
	
	}
	
	public void generateCMM(Student student) {
	
	}
}
