import java.util.HashMap;
import java.util.List;

//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : SIS
//  @ File Name : Professor.java
//  @ Date : 1/8/2014
//  @ Author : Meher, Harika, Omair, Nikhila
//
//


public class Professor {
	public String professorID;
	String password;
	
	public String toString() {
		return "Professor ID: "+professorID
				+ "\n";
	}
	
	/**
	 * @nikhila
	 */
	public Professor(){}
	public Professor(String pid, String pswrd) 
	{
		professorID=pid;
		password=pswrd;
	}

	public List<Course> viewProfCourses(){
		return null;
	}
	
	public void updateCourse(Course course){
		
	}
	
	public void viewCourseAttendanceReport(){
		
	}
	
	public List<Student> getStudentListByCourse(){
		return null;
	}
	
	public void updateStudentAttendance(List<Student> stdnts){
		
	}
	
	public void setQuestionPaper(String qstnPaper){
		
	}
	
	public String viewQuestionPaper(){
		return null;
	}
	
	public void giveMarks(java.util.HashMap<Student, Integer> students_marks){
		
	}
	
	public HashMap<Student,Integer> viewMarks(){
		return null;
	}

}
